# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: LedTest

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: "pip"
          cache-dependency-path: test.requirements.txt
      - name: Install dependencies
        run: pip install -r test.requirements.txt
      - name: black
        run: black --check .
      - name: ruff
        run: ruff .
      - name: flake8
        run: flake8 .
      - name: mypy
        run: mypy .
      - name: Test with pytest
        run: pytest
